export const categoryData = [
  "household",
  "shopping",
  "house-help",
  "subscription",
  "miscellaneous-expenses",
  "donation-charity",
  "medical-expenses",
  "towards-gifts",
  "pocket-money",
  "vacation",
  "travel",
  "vehicle",
  "lifestyle",
  "kid-s-study",
  "insurance-payments",
  "investment-outflows",
];

export const expenseData = [
  "cooking-gas",
  "towards-gifts",
  "pocket-money",
  "medical-expenses",
  "donation-charity",
  "miscellaneous-expenses",
  "health-insurance",
  "term-insurance",
  "mutual-funds",
  "equity",
  "tution-fees",
  "coaching-classes",
  "private-tution-fees",
  "books",
  "hostel-fees",
  "shoes-sack",
  "uniform",
  "dinning-out",
  "movies",
  "disco-pubs",
  "stationary-fees",
  "party-dinner-at-home",
  "fee-for-extra-curricular",
  "gym-membership",
  "party-in-a-restaurant",
  "gymkhana-membership",
  "dietician-nutritionist",
  "salon",
  "sports-utility",
  "hobby-expenses",
  "alcohol",
  "cigarette",
  "any-other-club-membership",
  "local-travel-auto",
  "local-travel-bus",
  "local-travel-taxi",
  "india",
  "abroad",
  "drivers-salary",
  "fuel-charges",
  "servicing-charges",
  "car-enhancement",
  "magazines-books",
  "bike-insurance",
  "electricity",
  "telephone",
  "mobile",
  "internet",
  "cable-dish-tv",
  "netflix",
  "amazon-prime",
  "streaming-memberships",
  "newspapers",
  "house-rent",
  "cosmetics",
  "repairs-maintenance",
  "grocery",
  "non-veg",
  "dryfruits",
  "fruits-vegetables",
  "milk",
  "laundry",
  "car-insurance",
  "toiletries",
  "electronic-goods",
  "garments",
  "cleaner-cook",
  "car-washing",
  "childcare-nanny",
  "society-membership",
  "adultcare-nurse",
];


export const expenseMapping = {
  "cooking-gas": "household",
  "towards-gifts": "vacation",
  "pocket-money": "pocket-money",
  "medical-expenses": "medical-expenses",
  "donation-charity": "donation-charity",
  "miscellaneous-expenses": "miscellaneous-expenses",
  "health-insurance": "insurance-payments",
  "term-insurance": "insurance-payments",
  "mutual-funds": "investment-outflows",
  "equity": "investment-outflows",
  "tution-fees": "kid-s-study",
  "coaching-classes": "kid-s-study",
  "private-tution-fees": "kid-s-study",
  "books": "lifestyle",
  "hostel-fees": "kid-s-study",
  "shoes-sack": "kid-s-study",
  "uniform": "kid-s-study",
  "dinning-out": "lifestyle",
  "movies": "investment-outflows",
  "disco-pubs": "lifestyle",
  "stationary-fees": "kid-s-study",
  "party-dinner-at-home": "lifestyle",
  "fee-for-extra-curricular": "kid-s-study",
  "gym-membership": "lifestyle",
  "party-in-a-restaurant": "investment-outflows",
  "gymkhana-membership": "lifestyle",
  "dietician-nutritionist": "lifestyle",
  "salon": "lifestyle",
  "sports-utility": "lifestyle",
  "hobby-expenses": "lifestyle",
  "alcohol": "lifestyle",
  "cigarette": "lifestyle",
  "any-other-club-membership": "lifestyle",
  "local-travel-auto": "travel",
  "local-travel-bus": "travel",
  "local-travel-taxi": "travel",
  "india": "vacation",
  "abroad": "vacation",
  "drivers-salary": "vehicle",
  "fuel-charges": "vehicle",
  "servicing-charges": "investment-outflows",
  "car-enhancement": "vehicle",
  "magazines-books": "lifestyle",
  "bike-insurance": "vehicle",
  "electricity": "subscription",
  "telephone": "subscription",
  "mobile": "subscription",
  "internet": "subscription",
  "cable-dish-tv": "subscription",
  "netflix": "subscription",
  "amazon-prime": "subscription",
  "streaming-memberships": "subscription",
  "newspapers": "subscription",
  "house-rent": "subscription",
  "cosmetics": "lifestyle",
  "repairs-maintenance": "subscription",
  "grocery": "household",
  "non-veg": "household",
  "dryfruits": "household",
  "fruits-vegetables": "household",
  "milk": "household",
  "laundry": "household",
  "car-insurance": "vehicle",
  "toiletries": "shopping",
  "electronic-goods": "shopping",
  "garments": "shopping",
  "cleaner-cook": "house-help",
  "car-washing": "house-help",
  "childcare-nanny": "house-help",
  "society-membership": "subscription",
  "adultcare-nurse": "house-help"
}
